### ISSUE TITLE
Rasa can't load the model

### ISSUE THREAD

**Issue by rkjaran** [SDiFI/sdifi_rasa_akranes#45]
This happens both for the released prebuilt model (v0.1) and one trained directly from the latest commit of the repository.

Here's a snippet from the logs:

```
rasa_1           | 2023-04-26 12:07:30 DEBUG    rasa.engine.graph  - Node 'run_LanguageModelFeaturizer4' loading 'LanguageModelFeaturizer.load' and kwargs: '{}'.
rasa_1           | 2023-04-26 12:07:30 DEBUG    rasa.nlu.featurizers.dense_featurizer.lm_featurizer  - Loading Tokenizer and Model for bert
rasa_1           | 2023-04-26 12:07:30 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): huggingface.co:443
rasa_1           | 2023-04-26 12:07:30 DEBUG    urllib3.connectionpool  - https://huggingface.co:443 "GET /api/models/m3hrdadfi/icelandic-ner-bert HTTP/1.1" 200 2882
rasa_1           | 2023-04-26 12:07:30 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): huggingface.co:443
rasa_1           | 2023-04-26 12:07:31 DEBUG    urllib3.connectionpool  - https://huggingface.co:443 "HEAD /m3hrdadfi/icelandic-ner-bert/resolve/main/vocab.txt HTTP/1.1" 200 0
rasa_1           | 2023-04-26 12:07:31 DEBUG    filelock  - Attempting to acquire lock 140342385233056 on /app/cache/dc0b1fe229ad4273c560cc4824f53bb2870fcb915bc2779385e6dca4a015a2f6.6c5b6600e968f4b5e08c86d8891ea99e51537fc2bf251435fb46922e8f7a7b29.lock
rasa_1           | 2023-04-26 12:07:31 ERROR    rasa.core.agent  - Could not load model due to Error initializing graph component for node run_LanguageModelFeaturizer4..
```

It does not matter whether we try to load the model through docker-compose or Rasa directly. This seems like some issue with the `m3hrdadfi/icelandic-ner-bert` LM, any ideas?

/cc @SmariF89

**Comment by rkjaran** [comment]
Ok, no. That wasn't entirely true. Running rasa directly works:

    rasa run -vv --credentials config/credentials.yml --endpoints config/endpoints.yml --port 8180 --cors "*" models/

Mapping the `./cache` directory into the rasa container in `docker-compose.yml` seems to be causing this. Seems like rasa fails to acquire that filelock when it is mapped. Same thing happens if I replace the directory volume mapping with a Docker volume.

**Comment by rkjaran** [comment]
Anyway, I had to create the `./cache` directory with `0777` permissions prior to running `docker-compose up`. Otherwise, it is created as owned by root and only writeable by root which is a problem since the rasa container uses uid 1001 for running rasa.

**Comment by lumpidu** [comment]
Yes. that's exactly the problem, is also mentioned in the `Readme.md` [here](https://github.com/SDiFI/sdifi_rasa_akranes/pull/47). Sorry for the inconvenience

**Comment by lumpidu** [comment]
@rkjaran : can we close this or do you need more clarifications ?
